-- this script is auto generated by excel file: dailyonline.xlsx
--      please don`t modify it.

local tt = {
	a_mt = { __index = i3k_Gdb.mt.defaultMT},
}
tt.a = { Id = 0, Count = 0, }
tt.b = setmetatable({ Id = 110181, }, tt.a_mt)
tt.a_mt.default = {Count = 1, }
i3k_db_dailyOnline = 
{
	[1] = { id = 1, minute = 5, rewards = { [1] = { Id = 2, Count = 10000, }, [2] = { Id = 31, Count = 200, }, [3] = tt.a, }, }, 
	[2] = { id = 2, minute = 10, rewards = { [1] = { Id = 2, Count = 15000, }, [2] = { Id = 110018, Count = 2, }, [3] = tt.a, }, }, 
	[3] = { id = 3, minute = 20, rewards = { [1] = { Id = 2, Count = 20000, }, [2] = setmetatable({ Id = 110015, }, tt.a_mt), [3] = tt.a, }, }, 
	[4] = { id = 4, minute = 40, rewards = { [1] = { Id = 2, Count = 30000, }, [2] = setmetatable({ Id = 110013, }, tt.a_mt), [3] = tt.a, }, }, 
	[5] = { id = 5, minute = 60, rewards = { [1] = tt.b, [2] = { Id = 10, Count = 30, }, [3] = tt.a, }, }, 
	[6] = { id = 6, minute = 90, rewards = { [1] = tt.b, [2] = setmetatable({ Id = 110552, }, tt.a_mt), [3] = tt.a, }, }, 
	[7] = { id = 7, minute = 120, rewards = { [1] = setmetatable({ Id = 110182, }, tt.a_mt), [2] = setmetatable({ Id = 110276, }, tt.a_mt), [3] = tt.a, }, }, 
};
