-- this script is auto generated by excel file: friends.xlsx
--      please don`t modify it.

local tt = {
}
i3k_db_friends_about = 
{
	[10] = { CoolTime = 10, CheckenId = 110425, FriendMaxCount = 50, FriendStatelength = 15, GetExperence = 1, AttentionLow = 0, AttentionHight = 10000, AttentionDefault = 100, AttentionAdd = 100, EnemyMax = 10, BlankList = 50, }, 
};
