-- this script is auto generated by excel file: friends.xlsx
--      please don`t modify it.

local tt = {
}
i3k_db_change_name = 
{
	[200] = { MoneyCount = 200, CoolTime = 86400, CardId = 110068, }, 
};
